/**
 * Transaction type utilities for the Movement blockchain
 */

// Transaction type enumeration
export const TransactionTypeName = {
  BlockMetadata: 'block_metadata_transaction',
  Genesis: 'genesis_transaction',
  User: 'user_transaction',
  Pending: 'pending_transaction',
  StateCheckpoint: 'state_checkpoint_transaction',
  Validator: 'validator_transaction',
  BlockEpilogue: 'block_epilogue_transaction',
} as const;

export type TransactionType = typeof TransactionTypeName[keyof typeof TransactionTypeName];

/**
 * Get user-friendly label and color for transaction type
 */
export function getTransactionTypeLabel(type: string): { label: string; color: string } {
  // Check for system transaction types first
  switch (type) {
    case TransactionTypeName.BlockMetadata:
      return { label: 'Block Metadata', color: 'bg-gray-500/10 text-gray-400 border-gray-500/20' };
    case TransactionTypeName.Genesis:
      return { label: 'Genesis', color: 'bg-indigo-500/10 text-indigo-500 border-indigo-500/20' };
    case TransactionTypeName.StateCheckpoint:
      return { label: 'State Checkpoint', color: 'bg-slate-500/10 text-slate-400 border-slate-500/20' };
    case TransactionTypeName.Validator:
      return { label: 'Validator', color: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20' };
    case TransactionTypeName.BlockEpilogue:
      return { label: 'Block Epilogue', color: 'bg-stone-500/10 text-stone-400 border-stone-500/20' };
    case TransactionTypeName.Pending:
      return { label: 'Pending', color: 'bg-amber-500/10 text-amber-500 border-amber-500/20' };
  }

  // For user transactions, check the function name
  const lowerType = type.toLowerCase();

  if (lowerType.includes('transfer') || lowerType.includes('coin::transfer')) {
    return { label: 'Transfer', color: 'bg-blue-500/20 text-blue-300 border-blue-500/30' };
  }
  if (lowerType.includes('stake') || lowerType.includes('delegation_pool')) {
    return { label: 'Staking', color: 'bg-purple-500/20 text-purple-300 border-purple-500/30' };
  }
  if (lowerType.includes('swap')) {
    return { label: 'Swap', color: 'bg-green-500/20 text-green-300 border-green-500/30' };
  }
  if (lowerType.includes('nft') || lowerType.includes('token::')) {
    return { label: 'NFT', color: 'bg-pink-500/20 text-pink-300 border-pink-500/30' };
  }
  if (lowerType.includes('script')) {
    return { label: 'Script', color: 'bg-orange-500/20 text-orange-300 border-orange-500/30' };
  }
  if (lowerType.includes('publish')) {
    return { label: 'Deploy', color: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30' };
  }

  return { label: 'User', color: 'bg-sky-500/20 text-sky-300 border-sky-500/30' };
}

/**
 * Get tooltip description for transaction type
 */
export function getTransactionTypeTooltip(type: string): string {
  switch (type) {
    case TransactionTypeName.BlockMetadata:
      return 'System-generated transactions that provide additional data for each confirmed block.';
    case TransactionTypeName.Genesis:
      return 'The first transaction in the Movement blockchain.';
    case TransactionTypeName.User:
      return 'A transaction generated by users of the Movement blockchain.';
    case TransactionTypeName.Pending:
      return 'A transaction currently in the mempool waiting to be committed.';
    case TransactionTypeName.StateCheckpoint:
      return 'System-generated transactions that save the latest state of the Movement blockchain.';
    case TransactionTypeName.Validator:
      return 'Validator metadata transactions.';
    case TransactionTypeName.BlockEpilogue:
      return 'Block epilogue transactions describing end state of a block.';
    default:
      return 'User transaction on the Movement blockchain.';
  }
}
